### ISSUE TITLE
Installation problem with Odoo 17

### ISSUE THREAD

**Issue by mikko80** [avoinsystems/avoinsystems-addons#29]
doo.tools.convert.ParseError: while parsing /opt/odoo/addons/l10n_fi_bank_barcode/views/account_move.xml:4
Since 17.0, the "attrs" and "states" attributes are no longer used.
View: account.move.form.barcode.supplier in views/account_move.xml

View error context:
{'name': 'invalid view'}

**Comment by aisopuro** [comment]
Hmm. It seems that when the modules were deactivated, manifests that were missing the `installable` keyword were overlooked. The module that raised the error should not have been installable, as it has not been migrated to 17. It is now marked uninstallable: a4bd21acd380d42f838759606f5a845320a813b5.
